# Generated by Django 5.1.3 on 2025-05-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_verification_required',
            field=models.BooleanField(default=True),
        ),
    ]
