# Generated by Django 5.1.3 on 2025-05-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
